# Test PCNetwork
Purpose: To do initial testing of the `PCNetwork` class.

In [34]:
import numpy as np
import torch
%load_ext autoreload
%autoreload 1
%aimport PCNetwork
%aimport PCLayer
%aimport PCConnection

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [63]:
net = PCNetwork.PCNetwork()

In [64]:
l = PCLayer.PCLayer(n=5)
net.AddLayer(PCLayer.PCLayer(n=5))  # v0 (input layer)
net.AddLayer(PCLayer.PCLayer(n=3))  # / e1
net.AddLayer(PCLayer.PCLayer(n=3))  # \ v1 (output layer)

net.Connect(v_idx=0, e_idx=1, type='general', sym=True, act_text='identity')
net.Connect(e_idx=1, v_idx=2, type='1to1')

In [69]:
net.con[0].M

tensor([[-1.0896,  0.1549,  1.3956],
        [-0.1618,  0.1534,  0.5749],
        [ 1.2641, -0.5207,  0.0359],
        [-0.8177, -0.2911,  0.6393],
        [ 2.1746,  0.3844,  0.7655]])

In [70]:
net.con[1].W

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [72]:
net.Allocate(3)
net.Reset(0.1)
net.lyr[-1].x

tensor([[ 0.0874,  0.0362,  0.1174],
        [-0.2096,  0.0529, -0.0390],
        [ 0.1903,  0.0365,  0.1112]])

In [29]:
net.Save('my.net')

In [9]:
net2 = PCNetwork.PCNetwork.Load('my.net')

In [ ]:
net.